Develop (#4)
* test vault action

* add runs-on

* correct action format

* correct secrets string

* try use environment variable to bypass ca verification

* Add vault cert

* test retrieve secret action

* test

* add token

* fix bug

* remove token and add tag

* add back token

* move custom action code to validate vault pipeline

* test

* asking for support

* add key_name and secret path

* check repo directory

* validate cookbook

* correct cookstyle

* correct job name

* new version

* validate output of branch and chef server

* remove extract branch

* test uploading test 1

* fix bug of first test

* test vault-action

* skip verify

* show secret

* show secret fix bug

* show secret remove sed

* retrieve key fix bug

* update role id

* tagging repository first try

* tagging repository 2nd try

* tagging fix bug

* show paramenters

* correct github token

* test upload action v0.1.1

* try github token as parameter

diff --git a/.github/workflows/validate_cookbook.yml b/.github/workflows/validate_cookbook.yml
--- a/.github/workflows/validate_cookbook.yml
+++ b/.github/workflows/validate_cookbook.yml
@@ -8,6 +8,9 @@ jobs:
     steps:
       - name: Check out repository
         uses: actions/checkout@v2
+      - name: tagging repository
+        run: |
+
       - name: Extract Chef Server
         shell: bash
         id: extract_chefserver
@@ -17,22 +20,71 @@ jobs:
           elif [ "${GITHUB_REF#refs/heads/}" == "develop" ]; then
             echo "##[set-output name=chefserver;]$(echo sandbox)"
           else
-            echo "Branch name invalid. This action can only be triggered by \"main\" or \"sandbox\" branch"
+            echo "Branch name invalid. This action can only be triggered by \"main\" or \"develop\" branch"
             exit 1
           fi
       - name: show chef server
         shell: bash
         run: |
           echo "chef server is ${{ steps.extract_chefserver.outputs.chefserver }}"
+      - name: Import Secrets
+        id: retrieve_secret
+        uses: hashicorp/vault-action@v2.1.2
+        with:
+          url: https://vault.prod.cac.platform.manulife.io:443
+          method: approle
+          roleId: bf50f9e9-2cca-beac-6cfa-8db32dae9614
+          secretId: ${{ secrets.VAULT_CHEF_SECRET_ID }}
+          namespace: ETS-CLOUDPLATFORM-IAC-3365
+          tlsSkipVerify: true
+          secrets: 
+            secret/data/chef_delivery chef_delivery_key | CHEF_DELIVERY_KEY
+      - name: check key
+        run: echo "${{ steps.retrieve_secret.outputs.CHEF_DELIVERY_KEY }}"
       - name: validate cookbook
         id: validate_cookbook
         uses: manulife-ets-sandbox/validate_cookbook@latest
         with:
-          chef_key: ${{ secrets.CHEF_SVC_KEY }}
+          chef_key: ${{ steps.retrieve_secret.outputs.CHEF_DELIVERY_KEY }}
           chef_server: ${{ steps.extract_chefserver.outputs.chefserver }}
       - name: upload cookbook
-        uses: manulife-ets-sandbox/upload_cookbook@latest
+        uses: manulife-ets-sandbox/upload_cookbook@testing
         with:
-          chef_key: ${{ secrets.CHEF_SVC_KEY }}
+          chef_key: ${{ steps.retrieve_secret.outputs.CHEF_DELIVERY_KEY }}
           chef_server: ${{ steps.extract_chefserver.outputs.chefserver }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
+          # VERSION=`cat metadata.rb|grep "version "|grep -v "_version"|awk '{print $2}'|sed $'s/\'//g'`
+          # object=$GITHUB_SHA
+          # repo=${{ github.repository }}
+          # token=${{ secrets.GITHUB_TOKEN }}
+          # tag="v$VERSION"
+          # message=$tag
+
+          # echo "Github SHA: $object"
+          # echo "Repository: $repo"
+          # echo "TOKEN: $token"
+          # echo "TAG: $tag"
+          # # Create version tag
+          # resp=`curl \
+          #   -X POST \
+          #   -H "Authorization: token $token" \
+          #   -H "Accept: application/vnd.github.v3+json" \
+          #   https://api.github.com/repos/$repo/git/tags \
+          #   -d "{\"tag\":\"$tag\",\"message\":\"$message\",\"object\":\"${object}\",\"type\":\"commit\"}"` 
+          # if [ $? -ne 0 ]; then
+          #   echo "Failed creating tag for this version"
+          #   exit 2 
+          # fi
+          # echo $resp
+          # resp=`curl \
+          #   -X POST \
+          #   -H "Authorization: token $token" \
+          #   -H "Accept: application/vnd.github.v3+json" \
+          #   https://api.github.com/repos/$repo/git/refs \
+          #   -d "{\"ref\":\"refs/tags/$tag\",\"sha\":\"$object\"}"`
+          # if [ $? -ne 0 ]; then
+          #   echo "Failed creating tag for this version"
+          #   exit 2 
+          # fi
+          # echo $resp
